# Generated by Django 6.0 for the cleaned pre-production schema.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirm_transcript', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('evaluating', 'Evaluating'), ('evaluated', 'Evaluated'), ('evaluation_failed', 'Evaluation failed')], default='created', max_length=20)),
                ('result', models.CharField(blank=True, choices=[('', 'Pending'), ('PROGRESS', 'Progress'), ('NOT_PROGRESS', 'Not progress')], max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('assistant', 'Assistant'), ('user', 'User')], max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='interviews.interviewsession')),
            ],
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.CreateModel(
            name='EvaluationAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_answers', to='interviews.interviewsession')),
            ],
            options={'ordering': ['question_index']},
        ),
        migrations.CreateModel(
            name='HumanReviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review_request', to='interviews.interviewsession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='evaluationanswer',
            constraint=models.UniqueConstraint(fields=('interview', 'question_index'), name='unique_interview_question'),
        ),
    ]
